apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: prometheus-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - --config.file={{ .Values.config.configFilePath }}
            - --storage.tsdb.path={{ .Values.config.storagePath }}
          volumeMounts:
            - name: prometheus-config
              mountPath: {{ .Values.config.configFilePath }}
              subPath: prometheus.yml
            - name: prometheus-storage
              mountPath: {{ .Values.config.storagePath }} # Persistent data path
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
      volumes:
        - name: prometheus-config
          configMap:
            name: {{ .Values.config.configMapName }}
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
