apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: {{ .Values.serviceAccount.namespace | default "monitoring" }}
  labels:
    app: prometheus
spec:
  ports:
    - name: web
      port: 9090
      protocol: TCP
  selector:
    app: prometheus
  type: {{ .Values.service.type }}