output "cluster_endpoint" {
    description = "Endpoint for EKS control plane"
    value = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
    description = "Security groups attached to cluster control plane"
    value = module.eks.cluster_security_group_id
}

output "kubectl_config" {
    description = "kubectl config as generated by module eks-cluster"
    value = module.eks.kubeconfig
}

output "config_map_aws_auth" {
    description = "kubernetes configuration to authenticate to this EKS cluster"
    value = module.eks.config_map_aws_auth
}

output "region" {
    description = "AWS eks cluster region"
    value = var.region
}

output "cluster_name" {
    description = "kubernetes cluster name"
    value = local.cluster_name
}