- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: terraform-validate
      args: ["--tflint-ignore", "TFLINT_IGNORE"]
    - id: terraform-fmt
    - id: check-merge-conflict
    - id: end-of-file-fixer
