apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gateways.networking.istio.io
spec:
  group: networking.istio.io
  names:
    kind: Gateway
    plural: gateways
  scope: Namespaced
  versions:
  - name: v1alpha3
    served: true
    storage: true