apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rpc-app
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - "*"
  gateways:
    - rpc-app-gateway
  http:
    - match:
        - uri:
            prefix: /rpc
      route:
        - destination:
            host: rpc-app-service
            port:
              number: 8081

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - "*"
  gateways:
    - rpc-app-gateway
  http:
    - match:
        - uri:
            prefix: /prometheus
      route:
        - destination:
            host: prometheus-server
            port:
              number: 9090
