apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: rpc-app-gateway
  namespace: istio-system  # or the namespace where you deploy Istio
spec:
  selector:
    istio: ingressgateway  # use Istio's ingress gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "rpc.local"  # Assumes a matching entry in /etc/hosts 
        - "prometheus.local"

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: {{ .Values.global.istioNamespace }}
spec:
  selector:
    istio: ingressgateway  # Use Istio's built-in ingress gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*"        