apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: {{ .Values.global.istioNamespace }}
  labels:
    app: istiod
spec:
  ports:
    - name: grpc-xds
      port: 15010
      targetPort: 15010
    - name: grpc
      port: 15012
      targetPort: 15012
  selector:
    app: istiod
  type: ClusterIP