kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.config.configMapName }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s # By default, scrape targets every 15 seconds.
      external_labels:
        monitor: 'codelab-monitor'
    
    scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:9090']

    - job_name: 'kubernetes-service-endpoints'
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name

    - job_name: 'istio-mesh'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_istio]
          action: keep
          regex: (.+);istio
