name: Lint GitHub Actions Workflows

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Install actionlint
      run: go install github.com/rhysd/actionlint/cmd/actionlint@1.7.1

    - name: Run actionlint
      run: actionlint
