name: Plan and Apply IAC

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  dev:
    uses: ./.github/workflows/tf-plan-apply.yml
    with:
      environment: dev
    secrets:
      GH_ROLE_ARN: ${{ secrets.GH_ROLE_ARN }}
      ROLE_ARN: ${{ secrets.ROLE_ARN }}

  stage:
    if: github.event_name == 'pull_request' && github.base_ref == 'refs/heads/master'
    uses: ./.github/workflows/tf-plan-apply.yml
    needs: dev
    with:
      environment: staging
    secrets:
      GH_ROLE_ARN: ${{ secrets.GH_ROLE_ARN }}
      ROLE_ARN: ${{ secrets.ROLE_ARN }}

  prod:
    if: github.event_name == 'pull_request' && github.base_ref == 'refs/heads/master'
    uses: ./.github/workflows/tf-plan-apply.yml
    needs: stage
    with:
      environment: prod
    secrets:
      GH_ROLE_ARN: ${{ secrets.GH_ROLE_ARN }}
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
