name: Plan and Apply IAC

on:
  pull_request:
    branches:
      - 'terragrunt'

jobs:
  dev_plan:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/tf-plan.yml
    with:
      environment: dev
    secrets:
      GH_ROLE_ARN: ${{ secrets.GH_ROLE_ARN }}
      TF_ROLE_ARN: ${{ secrets.TF_ROLE_ARN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  dev_apply:
    needs: [dev_plan]

    uses: ./.github/workflows/tf-apply.yml
    with:
      environment: dev
    secrets:
      GH_ROLE_ARN: ${{ secrets.GH_ROLE_ARN }}
      TF_ROLE_ARN: ${{ secrets.TF_ROLE_ARN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  stage_plan:
    uses: ./.github/workflows/tf-plan.yml
    needs: [dev_apply]
    with:
      environment: staging
    secrets:
      GH_ROLE_ARN: ${{ secrets.GH_ROLE_ARN }}
      TF_ROLE_ARN: ${{ secrets.TF_ROLE_ARN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  stage_apply:
    uses: ./.github/workflows/tf-apply.yml
    needs: [stage_plan]
    with:
      environment: staging
    secrets:
      GH_ROLE_ARN: ${{ secrets.GH_ROLE_ARN }}
      TF_ROLE_ARN: ${{ secrets.TF_ROLE_ARN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  prod_plan:
    uses: ./.github/workflows/tf-plan.yml
    needs: [stage_apply]
    with:
      environment: prod
    secrets:
      GH_ROLE_ARN: ${{ secrets.GH_ROLE_ARN }}
      TF_ROLE_ARN: ${{ secrets.TF_ROLE_ARN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  prod_apply:
    uses: ./.github/workflows/tf-apply.yml
    needs: [prod_plan]
    with:
      environment: prod
    secrets:
      GH_ROLE_ARN: ${{ secrets.GH_ROLE_ARN }}
      TF_ROLE_ARN: ${{ secrets.TF_ROLE_ARN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
