name: Plan and Apply IAC

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  dev:
    uses: ./.github/workflows/tf-plan-apply.yml
    with:
      environment: dev
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      GH_ROLE_ARN: ${{ secrets.GH_ROLE_ARN }}

  stage:
    uses: ./.github/workflows/tf-plan-apply.yml
    needs: dev
    with:
      environment: staging
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      GH_ROLE_ARN: ${{ secrets.GH_ROLE_ARN }}

  prod:
    uses: ./.github/workflows/tf-plan-apply.yml
    needs: stage
    with:
      environment: prod
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      GH_ROLE_ARN: ${{ secrets.GH_ROLE_ARN }}
