name: Plan and Apply IAC

on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string

        secrets:
            GH_ROLE_ARN:
                required: true
            ROLE_ARN:
                required: true

permissions:
    id-token: write
    contents: read
            
jobs:
  plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          
          # Update package lists and install basic dependencies
          sudo apt-get update
          sudo apt-get install -y wget unzip jq

          # Install Terragrunt
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.45.10/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          terragrunt -v

          # Install Chamber
          wget https://github.com/segmentio/chamber/releases/download/v2.10.4/chamber-v2.10.4-linux-amd64
          chmod +x chamber-v2.10.4-linux-amd64
          sudo mv chamber-v2.10.4-linux-amd64 /usr/local/bin/chamber
          chamber version
          

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.GH_ROLE_ARN }}

      - name: Run Terragrunt plan
        run: |

          # Assume env-appropriate role
          source ./terragrunt/assume-role.sh ${{ secrets.ROLE_ARN }} ${{ github.run_id }}

          # Source env vars
          export ENVIRONMENT="${{ inputs.environment }}"
          chamber env "$ENVIRONMENT" > /tmp/env_vars

          if [ -s /tmp/env_vars ]; then
              set -a
              source /tmp/env_vars
              set +a
              echo "Environment variables loaded successfully."
          else
              echo "Failed to load environment variables."
              exit 1
          fi

          # Run plan
          cd ./terragrunt/environments/${{ inputs.environment }}
          terragrunt run-all plan --terragrunt-non-interactive -out=tfplan
          terragrunt show -json tfplan > tfplan.json

      - name: Upload plan output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan_${{ inputs.environment }}
          path: ./terragrunt/environments/${{ inputs.environment }}/tfplan.json
