services:
  app:
    container_name: app_1
    restart: always
    build:
      context: ./app
    networks:
      - app-net
    volumes:
      - ./app:/home/app

  nginx:
    restart: always
    container_name: nginx_1
    build:
      context: ./nginx
    networks:
      - app-net
    ports:
      - 8000:80
      - 8001:443
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - app
networks:
  app-net:
