# istio/control-plane/values.yaml

global:
  istioNamespace: "istio-system"

# Define the image for Istiod (control-plane)
istiod:
  enabled: true
  image:
    repository: istio/istiod
    tag: 1.23.2
  replicaCount: 2
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

# Ingress Gateway
gateways:
  istio-ingressgateway:
    enabled: true
    image:
      repository: istio/proxyv2
      tag: 1.23.2
    replicaCount: 2
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi

  # Egress Gateway        
  # istio-egressgateway:
  #   enabled: false
  #   image:
  #     repository: istio/proxyv2
  #     tag: 1.23.2
  #   replicaCount: 2
  #   resources:
  #     limits:
  #       cpu: 500m
  #       memory: 512Mi
  #     requests:
  #       cpu: 200m
  #       memory: 256Mi
